// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bolzybkvyzhxbasgsofm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvbHp5Ymt2eXpoeGJhc2dzb2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDcwMzMsImV4cCI6MjA2NjUyMzAzM30.VqPb1P2-A79Tk9R8KLrqdfmoreCp8FKeGGb4ZxMef1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);